

version: '3.4'

services:
  robotika-face-page:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_HOST_IP=${HOST_IP}
    networks:
      - face_network
    ports:
      - "8001:3003"
    volumes:
      - ./public/image:/usr/src/robotika-face-page/public/images  # bind mount
      - robotika_images:/usr/src/robotika-face-page/public/images 

volumes:
  robotika_images:

networks:
  face_network:
    external: true